name: nightly-crawler
on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟执行一次
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    services:
      # 添加 MongoDB 服务
      mongodb:
        image: mongo:8.0.10
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: diecast

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install playwright pymongo beautifulsoup4 lxml
      - run: playwright install chromium

      # 等待 MongoDB 启动
      - name: Wait for MongoDB
        run: |
          for i in {1..10}; do
            nc -z localhost 27017 && echo "MongoDB ready" && exit 0
            echo "Waiting for MongoDB ($i/10)..."
            sleep 3
          done
          echo "MongoDB failed to start"
          exit 1

      - run: python crawler.py 2>&1 | tee crawler.log

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: crawler-log-${{ github.run_number }}
          path: crawler.log